// ⚠️ GENERATED by client/build.mjs —— 本文件是构建产物，不要直接改。
// 手写源码在 client/src/（types / engine / ai / lines / core / board / panel / ui / entry）。
// 改源码后重跑：node client/build.mjs
window.__ModuleLoader__.load({
  id: 'dsh-chess-xq-plugin',
  factory: (require) => {
    var react = require('react');
    var __modules = {};
    var __cache = {};
    function __def(id, fn) { __modules[id] = fn; }
    function __req(id) {
      if (id === 'react') return react;
      var m = __cache[id];
      if (m) return m.exports;
      m = { exports: {} };
      __cache[id] = m;
      __modules[id](m, m.exports, __req);
      return m.exports;
    }
    __def("ai", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 中国象棋 AI（alpha-beta 搜索 + 位置估值表 PST）
    // 移植自 chess-xq（web/src/game/ai.ts）。深度默认 3，可配置（1~4）。
    // 注意：搜索是同步的，深度 3 在浏览器主线程可能卡几百毫秒（参考实现同款）。
    var t = require('types');
    var e = require('engine');
    
    var PIECE_VALUE = {
      1: 100000, 2: 100, 3: 120, 4: 270, 5: 600, 6: 285, 7: 30,
      9: 100000, 10: 100, 11: 120, 12: 270, 13: 600, 14: 285, 15: 30,
    };
    
    var PIECE_ORDER = { 1: 7, 5: 6, 6: 5, 4: 4, 3: 3, 2: 2, 7: 1 };
    
    var PST_PAWN = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [20, 0, 20, 0, 30, 0, 20, 0, 20],
      [20, 0, 20, 0, 30, 0, 20, 0, 20],
      [30, 10, 30, 20, 50, 20, 30, 10, 30],
      [40, 20, 40, 30, 60, 30, 40, 20, 40],
      [50, 30, 50, 40, 70, 40, 50, 30, 50],
      [50, 40, 50, 50, 90, 50, 50, 40, 50],
    ];
    
    var PST_KNIGHT = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [-10, -20, -10, -20, 10, -20, -10, -20, -10],
      [-10, 0, 0, -10, 10, -10, 0, 0, -10],
      [10, 0, 0, 10, 20, 10, 0, 0, 10],
      [0, 0, 10, 20, 30, 20, 10, 0, 0],
    ];
    
    var PST_ROOK = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [10, 20, 20, 20, 20, 20, 20, 20, 10],
      [10, 20, 30, 30, 30, 30, 30, 20, 10],
      [10, 20, 30, 40, 40, 40, 30, 20, 10],
      [10, 20, 30, 50, 60, 50, 30, 20, 10],
    ];
    
    var PST_CANNON = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 10, 0, 0, 0, 10, 0, 0],
      [0, 10, 10, 0, 0, 0, 10, 10, 0],
      [10, 10, 20, 10, 10, 10, 20, 10, 10],
      [10, 20, 30, 30, 40, 30, 30, 20, 10],
    ];
    
    var PST_ADVISOR = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 10, 20, 10, 0, 0, 0],
    ];
    
    var PST_BISHOP = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 10, 0, 0, 0, 10, 0, 0],
    ];
    
    var PST_KING = [
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 20, 30, 20, 0, 0, 0],
    ];
    
    var PIECE_PST = {
      1: PST_KING, 9: PST_KING,
      2: PST_ADVISOR, 10: PST_ADVISOR,
      3: PST_BISHOP, 11: PST_BISHOP,
      4: PST_KNIGHT, 12: PST_KNIGHT,
      5: PST_ROOK, 13: PST_ROOK,
      6: PST_CANNON, 14: PST_CANNON,
      7: PST_PAWN, 15: PST_PAWN,
    };
    
    function evaluate(board) {
      var score = 0;
      for (var sq = 0; sq < t.BOARD_SIZE; sq++) {
        var piece = board[sq];
        if (piece <= t.Sq.EMPTY) continue;
        var rc = e.to9x10(sq), r9 = rc[0], c9 = rc[1];
        var isRed = t.colorOf(piece) === t.Color.RED;
        var baseVal = PIECE_VALUE[piece];
        var bonus = 0;
        if (t.typeOf(piece) === t.PieceType.PAWN) {
          if ((isRed && r9 <= 4) || (!isRed && r9 >= 5)) bonus = 70;
        }
        var pstRow = isRed ? r9 : (9 - r9);
        var posVal = PIECE_PST[piece][pstRow][c9];
        score += isRed ? (baseVal + bonus + posVal) : -(baseVal + bonus + posVal);
      }
      return score;
    }
    
    function moveScore(move, board) {
      var capturedType = move.captured ? t.typeOf(move.captured) : 0;
      var attackerType = t.typeOf(board[move.from]);
      if (capturedType > 0) {
        return 10000 + PIECE_ORDER[capturedType] * 10 - PIECE_ORDER[attackerType];
      }
      return 0;
    }
    
    function sortMoves(moves, board) {
      for (var i = 0; i < moves.length; i++) moves[i].score = moveScore(moves[i], board);
      moves.sort(function (a, b) { return (b.score || 0) - (a.score || 0); });
    }
    
    var searchNodes = 0;
    function resetSearchStats() { searchNodes = 0; }
    function getSearchNodes() { return searchNodes; }
    
    function alphaBeta(board, depth, alpha, beta, color) {
      searchNodes++;
      if (e.isCheckmate(board, color)) return -100000 + (100 - depth);
      if (e.isStalemate(board, color)) return -100000 + (100 - depth);
      if (depth === 0) return evaluate(board) * (color === t.Color.RED ? 1 : -1);
      var moves = e.getLegalMoves(board, color);
      if (moves.length === 0) return -100000 + (100 - depth);
      sortMoves(moves, board);
      for (var i = 0; i < moves.length; i++) {
        e.applyMove(board, moves[i]);
        var score = -alphaBeta(board, depth - 1, -beta, -alpha, t.oppositeColor(color));
        e.undoMove(board, moves[i]);
        if (score >= beta) return beta;
        if (score > alpha) alpha = score;
      }
      return alpha;
    }
    
    function findBestMove(board, color, depth) {
      depth = depth || 3;
      resetSearchStats();
      var moves = e.getLegalMoves(board, color);
      if (moves.length === 0) return { move: null, score: -100000, nodes: 0 };
      if (moves.length === 1) return { move: moves[0], score: 0, nodes: 1 };
      sortMoves(moves, board);
      var bestMove = null;
      var bestScore = -Infinity;
      for (var i = 0; i < moves.length; i++) {
        e.applyMove(board, moves[i]);
        var score = -alphaBeta(board, depth - 1, -Infinity, Infinity, t.oppositeColor(color));
        e.undoMove(board, moves[i]);
        if (score > bestScore) { bestScore = score; bestMove = moves[i]; }
      }
      return { move: bestMove, score: bestScore, nodes: searchNodes };
    }
    
    module.exports = { evaluate, findBestMove, resetSearchStats, getSearchNodes };
    
    });
    __def("board", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 棋盘组件（SVG，React.createElement 直译 Board.tsx）
    // 布局常量与参考实现一致：格 50px，内边距 30px，画布 510×560。
    // 点击统一走透明点击层（rect 最后渲染盖住全格），onCellClick(row, col)。
    var react = require('react');
    var e = require('engine');
    var t = require('types');
    
    var CELL_SIZE = 50;
    var PADDING = 30;
    var BOARD_WIDTH = 9 * CELL_SIZE;
    var BOARD_HEIGHT = 10 * CELL_SIZE;
    var SVG_WIDTH = BOARD_WIDTH + PADDING * 2;
    var SVG_HEIGHT = BOARD_HEIGHT + PADDING * 2;
    
    function el(type, props, ...children) {
      // 🐛 0.1.0：children 只收一个参数，棋子的 <text> 全被丢弃 → 棋子「纯贴图」没名字
      // 修：rest 参数收齐后逐个传给 createElement（单子/数组/多子都兼容）
      return react.createElement.apply(null, [type, props].concat(children));
    }
    
    function Board(props) {
      var board = props.board;
      var onCellClick = props.onCellClick;
      var selectedSquare = props.selectedSquare;
      var legalMoves = props.legalMoves || [];
      var lastMove = props.lastMove || null;
    
      // 收集棋子
      var pieces = [];
      for (var r = 0; r <= 9; r++) {
        for (var c = 0; c <= 8; c++) {
          var sq = e.from9x10(r, c);
          var piece = board[sq];
          if (piece > t.Sq.EMPTY) pieces.push({ row: r, col: c, piece: piece });
        }
      }
    
      function isSelected(row, col) {
        if (selectedSquare === undefined || selectedSquare === null) return false;
        var rc = e.to9x10(selectedSquare);
        return rc[0] === row && rc[1] === col;
      }
    
      var nodes = [];
    
      // 木质底板
      nodes.push(el('rect', {
        key: 'bg',
        x: PADDING - 5, y: PADDING - 5,
        width: BOARD_WIDTH + 10, height: BOARD_HEIGHT + 10,
        fill: '#DEB887', rx: 4,
      }));
    
      var g = [];
      // 横线
      for (var r0 = 0; r0 < 10; r0++) {
        g.push(el('line', {
          key: 'h-' + r0,
          x1: 0, y1: r0 * CELL_SIZE, x2: BOARD_WIDTH, y2: r0 * CELL_SIZE,
          stroke: '#5D4037', strokeWidth: (r0 === 0 || r0 === 9) ? 2 : 1,
        }));
      }
      // 竖线
      for (var c0 = 0; c0 < 9; c0++) {
        g.push(el('line', {
          key: 'v-' + c0,
          x1: c0 * CELL_SIZE, y1: 0, x2: c0 * CELL_SIZE, y2: BOARD_HEIGHT,
          stroke: '#5D4037', strokeWidth: (c0 === 0 || c0 === 8) ? 2 : 1,
        }));
      }
      // 楚河汉界
      g.push(el('line', {
        key: 'river',
        x1: 0, y1: 4.5 * CELL_SIZE, x2: BOARD_WIDTH, y2: 4.5 * CELL_SIZE,
        stroke: '#5D4037', strokeWidth: 2, strokeDasharray: '5,5',
      }));
      g.push(el('text', { key: 'river-l', x: BOARD_WIDTH * 0.25, y: 4.5 * CELL_SIZE - 8, textAnchor: 'middle', fill: '#5D4037', fontSize: 14, fontWeight: 'bold' }, '楚河'));
      g.push(el('text', { key: 'river-r', x: BOARD_WIDTH * 0.75, y: 4.5 * CELL_SIZE - 8, textAnchor: 'middle', fill: '#5D4037', fontSize: 14, fontWeight: 'bold' }, '汉界'));
      // 九宫斜线（红方底部 + 黑方顶部）
      g.push(el('line', { key: 'p-r1', x1: 3 * CELL_SIZE, y1: 7 * CELL_SIZE, x2: 5 * CELL_SIZE, y2: 9 * CELL_SIZE, stroke: '#5D4037', strokeWidth: 1 }));
      g.push(el('line', { key: 'p-r2', x1: 5 * CELL_SIZE, y1: 7 * CELL_SIZE, x2: 3 * CELL_SIZE, y2: 9 * CELL_SIZE, stroke: '#5D4037', strokeWidth: 1 }));
      g.push(el('line', { key: 'p-b1', x1: 3 * CELL_SIZE, y1: 0, x2: 5 * CELL_SIZE, y2: 2 * CELL_SIZE, stroke: '#5D4037', strokeWidth: 1 }));
      g.push(el('line', { key: 'p-b2', x1: 5 * CELL_SIZE, y1: 0, x2: 3 * CELL_SIZE, y2: 2 * CELL_SIZE, stroke: '#5D4037', strokeWidth: 1 }));
      // 兵位标记
      [2, 4, 6].forEach(function (c) {
        g.push(el('circle', { key: 'p-red-' + c, cx: c * CELL_SIZE, cy: 3 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      });
      [2, 4, 6].forEach(function (c) {
        g.push(el('circle', { key: 'p-blk-' + c, cx: c * CELL_SIZE, cy: 6 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      });
      // 炮位标记
      g.push(el('circle', { key: 'c-1', cx: 1 * CELL_SIZE, cy: 2 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      g.push(el('circle', { key: 'c-2', cx: 7 * CELL_SIZE, cy: 2 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      g.push(el('circle', { key: 'c-3', cx: 1 * CELL_SIZE, cy: 7 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      g.push(el('circle', { key: 'c-4', cx: 7 * CELL_SIZE, cy: 7 * CELL_SIZE, r: 4, fill: '#5D4037' }));
      // 列标记
      for (var c1 = 0; c1 < 9; c1++) {
        g.push(el('text', { key: 'col-t-' + c1, x: c1 * CELL_SIZE + CELL_SIZE / 2, y: -5, textAnchor: 'middle', fill: '#5D4037', fontSize: 12 }, String.fromCharCode(97 + c1)));
        g.push(el('text', { key: 'col-b-' + c1, x: c1 * CELL_SIZE + CELL_SIZE / 2, y: BOARD_HEIGHT + 20, textAnchor: 'middle', fill: '#5D4037', fontSize: 12 }, String.fromCharCode(97 + c1)));
      }
      // 行标记
      for (var r1 = 0; r1 < 10; r1++) {
        g.push(el('text', { key: 'row-l-' + r1, x: -15, y: r1 * CELL_SIZE + CELL_SIZE / 2 + 4, textAnchor: 'middle', fill: '#5D4037', fontSize: 12 }, String(10 - r1)));
        g.push(el('text', { key: 'row-r-' + r1, x: BOARD_WIDTH + 20, y: r1 * CELL_SIZE + CELL_SIZE / 2 + 4, textAnchor: 'middle', fill: '#5D4037', fontSize: 12 }, String(10 - r1)));
      }
      // 上一步落子高亮
      if (lastMove) {
        [lastMove.from, lastMove.to].forEach(function (sq, idx) {
          var rc = e.to9x10(sq);
          g.push(el('rect', {
            key: 'last-' + idx,
            x: rc[1] * CELL_SIZE + 2, y: rc[0] * CELL_SIZE + 2,
            width: CELL_SIZE - 4, height: CELL_SIZE - 4,
            fill: 'rgba(255, 215, 0, 0.25)', rx: 4,
          }));
        });
      }
      // 合法走法提示
      legalMoves.forEach(function (sq) {
        var rc = e.to9x10(sq);
        g.push(el('circle', {
          key: 'legal-' + sq,
          cx: rc[1] * CELL_SIZE + CELL_SIZE / 2, cy: rc[0] * CELL_SIZE + CELL_SIZE / 2,
          r: 8, fill: '#4CAF50', opacity: 0.6,
        }));
      });
      // 棋子
      pieces.forEach(function (p) {
        var isRed = t.colorOf(p.piece) === 0;
        var selected = isSelected(p.row, p.col);
        g.push(el('g', {
          key: 'piece-' + p.row + '-' + p.col,
          transform: 'translate(' + (p.col * CELL_SIZE + CELL_SIZE / 2) + ', ' + (p.row * CELL_SIZE + CELL_SIZE / 2) + ')',
        },
          el('circle', {
            r: CELL_SIZE * 0.42,
            fill: isRed ? '#E53935' : '#1A1A1A',
            stroke: selected ? '#FFD700' : '#333',
            strokeWidth: selected ? 3 : 2,
            style: { cursor: 'pointer' },
          }),
          el('text', {
            textAnchor: 'middle', dominantBaseline: 'middle',
            fill: isRed ? '#FFF' : '#DDD', fontSize: 24, fontWeight: 'bold',
            style: { pointerEvents: 'none' },
          }, t.PIECE_CN[p.piece])));
      });
      // 点击层（最后渲染，覆盖全格）
      for (var r2 = 0; r2 < 10; r2++) {
        for (var c2 = 0; c2 < 9; c2++) {
          g.push(el('rect', {
            key: 'click-' + r2 + '-' + c2,
            x: c2 * CELL_SIZE, y: r2 * CELL_SIZE,
            width: CELL_SIZE, height: CELL_SIZE,
            fill: 'transparent',
            style: { cursor: 'pointer', pointerEvents: 'fill' },
            onClick: (function (rr, cc) { return function () { if (onCellClick) onCellClick(rr, cc); }; })(r2, c2),
          }));
        }
      }
    
      nodes.push(el('g', { key: 'grid', transform: 'translate(' + PADDING + ', ' + PADDING + ')' }, g));
    
      return el('svg', {
        width: SVG_WIDTH, height: SVG_HEIGHT,
        viewBox: '0 0 ' + SVG_WIDTH + ' ' + SVG_HEIGHT,
        className: 'dsh-chess-board',
        style: { display: 'block', maxWidth: '100%', height: 'auto' },
      }, nodes);
    }
    
    module.exports = { Board, CELL_SIZE, PADDING, BOARD_WIDTH, BOARD_HEIGHT, SVG_WIDTH, SVG_HEIGHT };
    
    });
    __def("core", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 游戏核心（共享状态 + 对局状态机 + Host 通信）
    // 仿 dsh-puzzle 的 core.js 结构：模块级共享 store（跨组件/重挂载存活），
    // 操作全部走本模块（改状态 → 挑莉娅台词 → 上报 host → bump 重渲染）。
    // 移植自 chess-xq（web/src/hooks/useGame.ts + useSave.ts），并把 LINES 台词池接线进对局事件。
    var t = require('types');
    var e = require('engine');
    var ai = require('ai');
    var L = require('lines');
    
    var POLL_MS = 1000;
    var PANEL_EVENT = 'dsh-chess-panel';
    var STORAGE_KEY = 'dsh-chess-xq-saves';
    var POS_KEY = 'dsh-chess-xq-panel-pos';
    var MAX_MESSAGES = 20;
    
    var panelState = { open: false, pos: null };
    var rerender = { fn: null };
    
    var store = {
      board: null,
      currentColor: t.Color.RED,
      selected: null,          // 选中格（17×14 sq）或 null
      legalMoves: [],          // 合法落点 sq 列表
      status: 'playing',       // playing | red_win | black_win | draw
      moveHistory: [],         // [{from,to,captured}]
      boardHistory: [],        // 每步后的盘面（[0]=初始），悔棋用
      lastMove: null,
      aiThinking: false,
      aiTimer: null,
      aiDepth: 3,              // AI 搜索深度（host 配置同步）
      liyaLine: '',            // 当前莉娅台词（对局事件触发，渲染时固定）
      captures: 0,             // 累计吃子数（首杀台词）
      prevHumanCaptured: false, // 上一步是人吃子（兑子台词）
      saidEndgame: false,
      messages: [],            // 工具发来的话 [{seq,text}]
      seenSeq: 0,
      saves: [],               // [{id,date,summary}]
      showSaves: false,
    };
    
    function bump() { if (rerender.fn) rerender.fn(function (x) { return x + 1; }); }
    
    // ── 面板开关 ──
    function setPanelOpen(open) {
      panelState.open = open;
      try { window.dispatchEvent(new CustomEvent(PANEL_EVENT)); } catch (err) {}
      bump();
    }
    function togglePanel() { setPanelOpen(!panelState.open); }
    
    // ── 面板位置记忆（0.2.0：界面不固定 → 拖到哪存哪，刷新不丢）──
    function loadPos() {
      try {
        var raw = JSON.parse(localStorage.getItem(POS_KEY) || 'null');
        if (raw && Number.isFinite(raw.x) && Number.isFinite(raw.y)) return { x: raw.x, y: raw.y };
      } catch (err) {}
      return null;
    }
    function savePos() {
      try {
        if (panelState.pos) localStorage.setItem(POS_KEY, JSON.stringify(panelState.pos));
      } catch (err) {}
    }
    
    // ── 对局基础 ──
    function clearAiTimer() {
      if (store.aiTimer) { clearTimeout(store.aiTimer); store.aiTimer = null; }
    }
    
    function pieceCount(board) {
      var n = 0;
      for (var i = 0; i < t.BOARD_SIZE; i++) if (board[i] > t.Sq.EMPTY) n++;
      return n;
    }
    
    function say(line) {
      store.liyaLine = line || '';
      reportWithLine(line);
      bump();
    }
    
    function newGame() {
      clearAiTimer();
      store.board = e.initBoard();
      store.currentColor = t.Color.RED;
      store.selected = null;
      store.legalMoves = [];
      store.status = 'playing';
      store.moveHistory = [];
      store.boardHistory = [e.initBoard()];
      store.lastMove = null;
      store.aiThinking = false;
      store.captures = 0;
      store.prevHumanCaptured = false;
      store.saidEndgame = false;
      store.liyaLine = L.pick(L.LINES.opening);
      reportWithLine(store.liyaLine);
      bump();
    }
    
    // ── 人类走子（执红）──
    function handleCell(row, col) {
      if (store.status !== 'playing' || store.currentColor !== t.Color.RED) return;
      var sq = e.from9x10(row, col);
    
      if (store.selected !== null && store.legalMoves.indexOf(sq) >= 0) {
        var move = { from: store.selected, to: sq, captured: store.board[sq] };
        commitHumanMove(move);
        return;
      }
    
      var piece = store.board[sq];
      if (piece !== t.Sq.EMPTY && piece !== t.Sq.SENTINEL && t.colorOf(piece) === t.Color.RED) {
        var moves = e.getLegalMoves(store.board, t.Color.RED).filter(function (m) { return m.from === sq; });
        store.selected = sq;
        store.legalMoves = moves.map(function (m) { return m.to; });
      } else {
        store.selected = null;
        store.legalMoves = [];
      }
      bump();
    }
    
    function commitHumanMove(move) {
      var beforeEval = ai.evaluate(store.board); // 红方视角
      var newBoard = e.makeMove(store.board, move);
      var newStatus = 'playing';
      if (e.isCheckmate(newBoard, t.Color.BLACK)) newStatus = 'red_win';
      else if (e.isStalemate(newBoard, t.Color.BLACK)) newStatus = 'draw';
    
      store.board = newBoard;
      store.currentColor = t.Color.BLACK;
      store.selected = null;
      store.legalMoves = [];
      store.status = newStatus;
      store.moveHistory = store.moveHistory.concat([move]);
      store.boardHistory = store.boardHistory.concat([newBoard]);
      store.lastMove = move;
      store.prevHumanCaptured = move.captured > t.Sq.EMPTY;
      if (move.captured > t.Sq.EMPTY) store.captures++;
    
      pickLineHuman(move, newBoard, newStatus, beforeEval);
    
      if (newStatus === 'playing') scheduleAi();
      report();
      bump();
    }
    
    function pickLineHuman(move, newBoard, status, beforeEval) {
      if (status === 'red_win') { say(L.pick(L.LINES.playerWin)); return; }
      if (status === 'draw') { say(L.pick(L.LINES.draw)); return; }
      if (e.isInCheck(newBoard, t.Color.BLACK)) { say(L.pick(L.LINES.playerCheck)); return; }
      if (move.captured > t.Sq.EMPTY) { say(L.pick(L.LINES.playerCapture)); return; }
    
      // 兵过河
      var toRC = e.to9x10(move.to);
      var piece = newBoard[move.to];
      if (t.typeOf(piece) === t.PieceType.PAWN && t.colorOf(piece) === t.Color.RED && toRC[0] <= 4) {
        say(L.pick(L.LINES.pawnCross)); return;
      }
      // 后退（红方 row 增大 = 后退）
      var fromRC = e.to9x10(move.from);
      if (toRC[0] > fromRC[0] && Math.random() < 0.5) { say(L.pick(L.LINES.playerRetreat)); return; }
      // 昏招（红方视角估值掉 ≥ 150）
      var afterEval = ai.evaluate(newBoard);
      if (beforeEval - afterEval >= 150 && Math.random() < 0.6) { say(L.pick(L.LINES.blunder)); return; }
      // 残局提示（一次性）
      if (!store.saidEndgame && pieceCount(newBoard) <= 8) {
        store.saidEndgame = true;
        say(L.pick(L.LINES.endgame)); return;
      }
      // 安静棋：保留上一条台词
    }
    
    // ── AI 走子（执黑）──
    function scheduleAi() {
      clearAiTimer();
      store.aiThinking = true;
      store.liyaLine = L.pick(L.LINES.thinking);
      report();
      bump();
      store.aiTimer = setTimeout(doAiMove, 700);
    }
    
    function doAiMove() {
      store.aiTimer = null;
      if (store.status !== 'playing' || store.currentColor !== t.Color.BLACK) {
        store.aiThinking = false;
        bump();
        return;
      }
      var result = ai.findBestMove(store.board, t.Color.BLACK, store.aiDepth);
      if (!result.move) {
        store.aiThinking = false;
        store.liyaLine = L.pick(L.LINES.no_moves);
        bump();
        return;
      }
      var move = result.move;
      var newBoard = e.makeMove(store.board, move);
      var newStatus = 'playing';
      if (e.isCheckmate(newBoard, t.Color.RED)) newStatus = 'black_win';
      else if (e.isStalemate(newBoard, t.Color.RED)) newStatus = 'draw';
    
      var aiCaptured = move.captured > t.Sq.EMPTY;
      var trade = aiCaptured && store.prevHumanCaptured;
    
      store.board = newBoard;
      store.currentColor = t.Color.RED;
      store.selected = null;
      store.legalMoves = [];
      store.status = newStatus;
      store.moveHistory = store.moveHistory.concat([move]);
      store.boardHistory = store.boardHistory.concat([newBoard]);
      store.lastMove = move;
      store.aiThinking = false;
      if (aiCaptured) store.captures++;
      store.prevHumanCaptured = false;
    
      pickLineAi(newStatus, aiCaptured, trade, newBoard);
    
      report();
      bump();
    }
    
    function pickLineAi(status, aiCaptured, trade, newBoard) {
      if (status === 'black_win') { say(L.pick(L.LINES.gameOver)); return; }
      if (status === 'draw') { say(L.pick(L.LINES.draw)); return; }
      if (e.isInCheck(newBoard, t.Color.RED)) { say(L.pick(L.LINES.check)); return; }
      if (aiCaptured) {
        if (store.captures === 1) { say(L.pick(L.LINES.firstBlood)); return; }
        if (trade) { say(L.pick(L.LINES.trade)); return; }
        say(L.pick(L.LINES.capture)); return;
      }
      // 兵过河
      var rc = e.to9x10(store.lastMove.to);
      var piece = newBoard[store.lastMove.to];
      if (t.typeOf(piece) === t.PieceType.PAWN && t.colorOf(piece) === t.Color.BLACK && rc[0] >= 5) {
        say(L.pick(L.LINES.pawnCross)); return;
      }
      if (!store.saidEndgame && pieceCount(newBoard) <= 8) {
        store.saidEndgame = true;
        say(L.pick(L.LINES.endgame));
      }
    }
    
    // ── 悔棋 / 保存 / 读取（移植 useGame.undoMove + useSave）──
    function undo() {
      if (store.moveHistory.length < 2) return;
      if (store.currentColor !== t.Color.RED) return;
      clearAiTimer();
      store.aiThinking = false;
      var newHistory = store.moveHistory.slice(0, -2);
      var newBoardHistory = store.boardHistory.slice(0, -2);
      if (!newBoardHistory.length) return;
      var previousBoard = newBoardHistory[newBoardHistory.length - 1];
      store.board = previousBoard;
      store.currentColor = t.Color.RED;
      store.selected = null;
      store.legalMoves = [];
      store.status = 'playing';
      store.moveHistory = newHistory;
      store.boardHistory = newBoardHistory;
      store.lastMove = newHistory.length ? newHistory[newHistory.length - 1] : null;
      say(L.pick(L.LINES.undo));
      report();
      bump();
    }
    
    function getSummary(d) {
      var resultMap = { playing: '进行中', red_win: '红方胜', black_win: '黑方胜', draw: '和棋' };
      return ((d.moveHistory ? d.moveHistory.length : 0)) + ' 步 · ' + (resultMap[d.result] || d.result);
    }
    
    function loadSaves() {
      try {
        var data = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
        store.saves = Object.keys(data).map(function (id) {
          return { id: id, date: data[id].date, summary: getSummary(data[id]) };
        });
      } catch (err) { store.saves = []; }
    }
    
    function saveGame() {
      var id = String(Date.now());
      var date = new Date().toLocaleString('zh-CN');
      var saveData = {
        date: date,
        fen: e.serializeFEN(store.board, store.currentColor),
        moveHistory: store.moveHistory.map(function (m) { return m.from + ',' + m.to + ',' + m.captured; }),
        result: store.status,
      };
      try {
        var existing = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
        existing[id] = saveData;
        localStorage.setItem(STORAGE_KEY, JSON.stringify(existing));
        store.saves = [{ id: id, date: date, summary: getSummary(saveData) }].concat(store.saves);
        store.liyaLine = '存好了。本天使替阁下记着这盘棋。';
        bump();
        return true;
      } catch (err) { return false; }
    }
    
    function loadGame(id) {
      try {
        var existing = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
        var d = existing[id];
        if (!d) return null;
        clearAiTimer();
        var parsed = e.deserializeFEN(d.fen);
        store.board = parsed.board;
        store.currentColor = parsed.turn;
        store.status = (d.result === 'playing' || d.result === 'red_win' || d.result === 'black_win' || d.result === 'draw') ? d.result : 'playing';
        store.moveHistory = (d.moveHistory || []).map(function (s) {
          var p = String(s).split(',').map(Number);
          return { from: p[0], to: p[1], captured: p[2] };
        });
        // 从初始盘面重放重建 boardHistory，保证悔棋可用
        var hist = [e.initBoard()];
        for (var i = 0; i < store.moveHistory.length; i++) {
          hist.push(e.makeMove(hist[hist.length - 1], store.moveHistory[i]));
        }
        store.boardHistory = hist;
        store.selected = null;
        store.legalMoves = [];
        store.lastMove = store.moveHistory.length ? store.moveHistory[store.moveHistory.length - 1] : null;
        store.aiThinking = false;
        store.liyaLine = '把存档翻出来了。接着下。';
        if (store.status === 'playing' && store.currentColor === t.Color.BLACK) scheduleAi();
        report();
        bump();
        return true;
      } catch (err) { return false; }
    }
    
    function deleteSave(id) {
      try {
        var existing = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
        delete existing[id];
        localStorage.setItem(STORAGE_KEY, JSON.stringify(existing));
        store.saves = store.saves.filter(function (s) { return s.id !== id; });
        bump();
      } catch (err) {}
    }
    
    // ── 与 Host 通信 ──
    function post(path, body) {
      try {
        return fetch(path, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(body || {}),
        }).catch(function () {});
      } catch (err) { return null; }
    }
    
    function report() {
      post('/dsh-chess/report', {
        turn: store.currentColor,
        status: store.status,
        moves: store.moveHistory.length,
        selected: store.selected,
        aiThinking: store.aiThinking,
        lastMove: store.lastMove
          ? { from: store.lastMove.from, to: store.lastMove.to, captured: store.lastMove.captured }
          : null,
      });
    }
    
    function reportWithLine(line) {
      post('/dsh-chess/report', {
        line: line || '',
        turn: store.currentColor,
        status: store.status,
        moves: store.moveHistory.length,
        lastMove: store.lastMove
          ? { from: store.lastMove.from, to: store.lastMove.to, captured: store.lastMove.captured }
          : null,
      });
    }
    
    // 轮询：拉工具消息/命令 + 配置（AI 深度）
    function pullState() {
      fetch('/dsh-chess/state', { cache: 'no-store' })
        .then(function (r) { return r.ok ? r.json() : null; })
        .then(function (d) {
          if (!d || typeof d !== 'object') return;
          var changed = false;
          if (Array.isArray(d.messages) && d.messages.length) {
            var fresh = d.messages.filter(function (m) { return m.seq > store.seenSeq; });
            if (fresh.length) {
              for (var i = 0; i < fresh.length; i++) {
                var m = fresh[i];
                if (m.kind === 'cmd' && m.cmd === 'new_game') {
                  newGame(); // 工具 chess_new_game 触发新局
                } else {
                  store.messages = store.messages.concat([{ seq: m.seq, text: m.text }]).slice(-MAX_MESSAGES);
                }
              }
              if (fresh[fresh.length - 1].seq > store.seenSeq) store.seenSeq = fresh[fresh.length - 1].seq;
              changed = true;
            }
          }
          var cfg = d.config;
          if (cfg && typeof cfg === 'object' && Number.isInteger(cfg.aiDepth) && cfg.aiDepth >= 1 && cfg.aiDepth <= 4) {
            if (cfg.aiDepth !== store.aiDepth) { store.aiDepth = cfg.aiDepth; changed = true; }
          }
          if (changed) bump();
        })
        .catch(function () { /* 轮询失败静默 */ });
    }
    
    function pollTick() { pullState(); }
    
    function boot() {
      newGame();
      loadSaves();
      pullState();
    }
    
    function formatMove(move) {
      var colNames = 'abcdefghi';
      var fromRC = e.to9x10(move.from), toRC = e.to9x10(move.to);
      var piece = move.captured !== t.Sq.EMPTY ? t.PIECE_CN[move.captured] : '';
      var capture = piece ? '吃' + piece : '';
      return colNames[fromRC[1]] + (10 - fromRC[0]) + ' → ' + colNames[toRC[1]] + (10 - toRC[0]) + capture;
    }
    
    module.exports = {
      POLL_MS, PANEL_EVENT, STORAGE_KEY, MAX_MESSAGES,
      panelState, rerender, store,
      bump, setPanelOpen, togglePanel, loadPos, savePos,
      newGame, handleCell, scheduleAi, undo,
      saveGame, loadGame, deleteSave, loadSaves, getSummary,
      pullState, pollTick, boot, formatMove, say,
    };
    
    });
    __def("engine", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 中国象棋规则引擎（纯函数，无状态）
    // 移植自 chess-xq（web/src/game/engine.ts），逐函数直译。
    var t = require('types');
    
    function initBoard() {
      var board = new Int8Array(t.BOARD_SIZE);
      for (var i = 0; i < t.BOARD_SIZE; i++) board[i] = t.Sq.SENTINEL;
      for (var r = 0; r <= 9; r++) for (var c = 0; c <= 8; c++) board[t.sqIdx(r, c)] = t.Sq.EMPTY;
    
      var blkBackRank = [t.Piece.R_BLK, t.Piece.N_BLK, t.Piece.B_BLK, t.Piece.A_BLK, t.Piece.K_BLK,
                         t.Piece.A_BLK, t.Piece.B_BLK, t.Piece.N_BLK, t.Piece.R_BLK];
      var redBackRank = [t.Piece.R_RED, t.Piece.N_RED, t.Piece.B_RED, t.Piece.A_RED, t.Piece.K_RED,
                         t.Piece.A_RED, t.Piece.B_RED, t.Piece.N_RED, t.Piece.R_RED];
      var blkPawns = [t.Piece.P_BLK, t.Sq.EMPTY, t.Piece.P_BLK, t.Sq.EMPTY, t.Piece.P_BLK,
                      t.Sq.EMPTY, t.Piece.P_BLK, t.Sq.EMPTY, t.Piece.P_BLK];
      var redPawns = [t.Piece.P_RED, t.Sq.EMPTY, t.Piece.P_RED, t.Sq.EMPTY, t.Piece.P_RED,
                      t.Sq.EMPTY, t.Piece.P_RED, t.Sq.EMPTY, t.Piece.P_RED];
    
      for (var c = 0; c <= 8; c++) {
        board[t.sqIdx(0, c)] = blkBackRank[c];
        board[t.sqIdx(2, c)] = c === 1 || c === 7 ? t.Piece.C_BLK : t.Sq.EMPTY;
        board[t.sqIdx(3, c)] = blkPawns[c];
        board[t.sqIdx(6, c)] = redPawns[c];
        board[t.sqIdx(7, c)] = c === 1 || c === 7 ? t.Piece.C_RED : t.Sq.EMPTY;
        board[t.sqIdx(9, c)] = redBackRank[c];
      }
      return board;
    }
    
    function to9x10(sq) { return t.sqToRC(sq); }
    function from9x10(r, c) { return t.sqIdx(r, c); }
    
    function inPalace(r, c, color) {
      var palace = color === t.Color.RED ? t.RED_PALACE : t.BLK_PALACE;
      return r >= palace.rowMin && r <= palace.rowMax && c >= palace.colMin && c <= palace.colMax;
    }
    
    function isCrossedRiver(r, color) {
      return color === t.Color.RED ? r <= 4 : r >= 5;
    }
    
    function genKingMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.KING_DIRS.length; i++) {
        var d = t.KING_DIRS[i], nr = r + d[0], nc = c + d[1];
        if (!t.inBoard(nr, nc)) continue;
        if (!inPalace(nr, nc, color)) continue;
        var to = from9x10(nr, nc);
        var target = board[to];
        if (target === t.Sq.SENTINEL) continue;
        if (target === t.Sq.EMPTY || t.colorOf(target) !== color) {
          moves.push({ from: sq, to: to, captured: target === t.Sq.EMPTY ? 0 : target });
        }
      }
    }
    
    function genAdvisorMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.ADVISOR_DELTAS.length; i++) {
        var d = t.ADVISOR_DELTAS[i], nr = r + d[0], nc = c + d[1];
        if (!t.inBoard(nr, nc)) continue;
        if (!inPalace(nr, nc, color)) continue;
        var to = from9x10(nr, nc);
        var target = board[to];
        if (target === t.Sq.SENTINEL) continue;
        if (target === t.Sq.EMPTY || t.colorOf(target) !== color) {
          moves.push({ from: sq, to: to, captured: target === t.Sq.EMPTY ? 0 : target });
        }
      }
    }
    
    function genBishopMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.BISHOP_MOVES.length; i++) {
        var m = t.BISHOP_MOVES[i], nr = r + m[0], nc = c + m[1];
        if (!t.inBoard(nr, nc)) continue;
        var hindrance = from9x10(r + m[2], c + m[3]);
        if (board[hindrance] !== t.Sq.EMPTY) continue;
        var to = from9x10(nr, nc);
        var target = board[to];
        if (target === t.Sq.SENTINEL) continue;
        if (target === t.Sq.EMPTY || t.colorOf(target) !== color) {
          moves.push({ from: sq, to: to, captured: target === t.Sq.EMPTY ? 0 : target });
        }
      }
    }
    
    function genKnightMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.KNIGHT_MOVES.length; i++) {
        var m = t.KNIGHT_MOVES[i], nr = r + m[0], nc = c + m[1];
        if (!t.inBoard(nr, nc)) continue;
        var hindrance = from9x10(r + m[2], c + m[3]);
        if (board[hindrance] !== t.Sq.EMPTY) continue;
        var to = from9x10(nr, nc);
        var target = board[to];
        if (target === t.Sq.SENTINEL) continue;
        if (target === t.Sq.EMPTY || t.colorOf(target) !== color) {
          moves.push({ from: sq, to: to, captured: target === t.Sq.EMPTY ? 0 : target });
        }
      }
    }
    
    function genRookMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.LINE_DIRS.length; i++) {
        var d = t.LINE_DIRS[i], nr = r + d[0], nc = c + d[1];
        while (t.inBoard(nr, nc)) {
          var to = from9x10(nr, nc);
          var target = board[to];
          if (target === t.Sq.SENTINEL) break;
          if (target !== t.Sq.EMPTY) {
            if (t.colorOf(target) !== color) moves.push({ from: sq, to: to, captured: target });
            break;
          }
          moves.push({ from: sq, to: to, captured: 0 });
          nr += d[0]; nc += d[1];
        }
      }
    }
    
    function genCannonMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      for (var i = 0; i < t.LINE_DIRS.length; i++) {
        var d = t.LINE_DIRS[i], nr = r + d[0], nc = c + d[1];
        var jumped = false;
        while (t.inBoard(nr, nc)) {
          var to = from9x10(nr, nc);
          var target = board[to];
          if (target === t.Sq.SENTINEL) break;
          if (!jumped) {
            if (target !== t.Sq.EMPTY) { jumped = true; }
            else { moves.push({ from: sq, to: to, captured: 0 }); }
          } else {
            if (target !== t.Sq.EMPTY) {
              if (t.colorOf(target) !== color) moves.push({ from: sq, to: to, captured: target });
              break;
            }
          }
          nr += d[0]; nc += d[1];
        }
      }
    }
    
    function genPawnMoves(board, sq, color, moves) {
      var rc = to9x10(sq), r = rc[0], c = rc[1];
      var forward = color === t.Color.RED ? -1 : 1;
      var crossed = isCrossedRiver(r, color);
      var fr = r + forward;
      if (t.inBoard(fr, c)) {
        var to = from9x10(fr, c);
        var target = board[to];
        if (target !== t.Sq.SENTINEL && (target === t.Sq.EMPTY || t.colorOf(target) !== color)) {
          moves.push({ from: sq, to: to, captured: target === t.Sq.EMPTY ? 0 : target });
        }
      }
      if (crossed) {
        for (var k = 0; k < 2; k++) {
          var dc = k === 0 ? -1 : 1;
          var nc = c + dc;
          if (t.inBoard(r, nc)) {
            var to2 = from9x10(r, nc);
            var target2 = board[to2];
            if (target2 !== t.Sq.SENTINEL && (target2 === t.Sq.EMPTY || t.colorOf(target2) !== color)) {
              moves.push({ from: sq, to: to2, captured: target2 === t.Sq.EMPTY ? 0 : target2 });
            }
          }
        }
      }
    }
    
    function genMoves(board, color) {
      var moves = [];
      for (var sq = 0; sq < t.BOARD_SIZE; sq++) {
        var piece = board[sq];
        if (piece <= t.Sq.EMPTY) continue;
        if (t.colorOf(piece) !== color) continue;
        switch (t.typeOf(piece)) {
          case t.PieceType.KING: genKingMoves(board, sq, color, moves); break;
          case t.PieceType.ADVISOR: genAdvisorMoves(board, sq, color, moves); break;
          case t.PieceType.BISHOP: genBishopMoves(board, sq, color, moves); break;
          case t.PieceType.KNIGHT: genKnightMoves(board, sq, color, moves); break;
          case t.PieceType.ROOK: genRookMoves(board, sq, color, moves); break;
          case t.PieceType.CANNON: genCannonMoves(board, sq, color, moves); break;
          case t.PieceType.PAWN: genPawnMoves(board, sq, color, moves); break;
        }
      }
      return moves;
    }
    
    function makeMove(board, move) {
      var newBoard = new Int8Array(board);
      newBoard[move.to] = newBoard[move.from];
      newBoard[move.from] = t.Sq.EMPTY;
      return newBoard;
    }
    
    function applyMove(board, move) {
      board[move.to] = board[move.from];
      board[move.from] = t.Sq.EMPTY;
    }
    
    function undoMove(board, move) {
      board[move.from] = board[move.to];
      board[move.to] = move.captured;
    }
    
    function getLegalMoves(board, color) {
      var pseudo = genMoves(board, color);
      return pseudo.filter(function (move) {
        var nb = makeMove(board, move);
        return !isInCheck(nb, color);
      });
    }
    
    function hasLegalMoves(board, color) {
      var pseudo = genMoves(board, color);
      for (var i = 0; i < pseudo.length; i++) {
        var nb = makeMove(board, pseudo[i]);
        if (!isInCheck(nb, color)) return true;
      }
      return false;
    }
    
    function findKing(board, color) {
      var king = color === t.Color.RED ? t.Piece.K_RED : t.Piece.K_BLK;
      for (var sq = 0; sq < t.BOARD_SIZE; sq++) if (board[sq] === king) return sq;
      return -1;
    }
    
    function forEachPiece(board, color, fn) {
      for (var sq = 0; sq < t.BOARD_SIZE; sq++) {
        var piece = board[sq];
        if (piece > t.Sq.EMPTY && t.colorOf(piece) === color) fn(sq, piece);
      }
    }
    
    function flyingGeneral(board) {
      var redKingSq = findKing(board, t.Color.RED);
      var blkKingSq = findKing(board, t.Color.BLACK);
      if (redKingSq < 0 || blkKingSq < 0) return false;
      var redRC = to9x10(redKingSq), blkRC = to9x10(blkKingSq);
      if (redRC[1] !== blkRC[1]) return false;
      var r1 = Math.floor(redKingSq / t.COLS);
      var r2 = Math.floor(blkKingSq / t.COLS);
      var rowMin = Math.min(r1, r2), rowMax = Math.max(r1, r2);
      for (var r = rowMin + 1; r < rowMax; r++) {
        if (board[r * t.COLS + (redKingSq % t.COLS)] !== t.Sq.EMPTY) return false;
      }
      return true;
    }
    
    function isInCheck(board, color) {
      if (flyingGeneral(board)) return true;
      var kingSq = findKing(board, color);
      if (kingSq < 0) return true;
      var oppMoves = genMoves(board, t.oppositeColor(color));
      for (var i = 0; i < oppMoves.length; i++) if (oppMoves[i].to === kingSq) return true;
      return false;
    }
    
    function isCheckmate(board, color) {
      if (!isInCheck(board, color)) return false;
      return !hasLegalMoves(board, color);
    }
    
    function isStalemate(board, color) {
      if (isInCheck(board, color)) return false;
      return !hasLegalMoves(board, color);
    }
    
    function serializeFEN(board, turn) {
      var rows = [];
      for (var r9 = 0; r9 <= 9; r9++) {
        var row = [];
        var emptyCount = 0;
        for (var c9 = 0; c9 <= 8; c9++) {
          var sq = from9x10(r9, c9);
          var piece = board[sq];
          if (piece <= t.Sq.EMPTY) { emptyCount++; }
          else {
            if (emptyCount > 0) { row.push(String(emptyCount)); emptyCount = 0; }
            row.push(t.PIECE_TO_FEN[piece]);
          }
        }
        if (emptyCount > 0) row.push(String(emptyCount));
        rows.push(row.join(''));
      }
      return rows.join('/') + ' ' + (turn === t.Color.RED ? 'w' : 'b') + ' - - 0 1';
    }
    
    function deserializeFEN(fen) {
      var parts = String(fen).split(' ');
      var boardStr = parts[0];
      var turnStr = parts[1];
      var board = new Int8Array(t.BOARD_SIZE);
      for (var r = 0; r < t.ROWS; r++) for (var c = 0; c < t.COLS; c++) board[r * t.COLS + c] = t.Sq.SENTINEL;
      for (var r2 = t.ROW_OFFSET; r2 < t.ROW_OFFSET + 10; r2++) {
        for (var c2 = t.COL_OFFSET; c2 < t.COL_OFFSET + 9; c2++) board[r2 * t.COLS + c2] = t.Sq.EMPTY;
      }
      var fenRows = boardStr.split('/');
      for (var r9 = 0; r9 < fenRows.length && r9 <= 9; r9++) {
        var rowStr = fenRows[r9];
        var c9 = 0;
        for (var i = 0; i < rowStr.length; i++) {
          var ch = rowStr[i];
          if (ch >= '1' && ch <= '9') { c9 += parseInt(ch, 10); }
          else if (t.FEN_TO_PIECE[ch] !== undefined) { board[from9x10(r9, c9)] = t.FEN_TO_PIECE[ch]; c9++; }
        }
      }
      return { board: board, turn: turnStr === 'w' ? t.Color.RED : t.Color.BLACK };
    }
    
    function printBoard(board) {
      var out = ['   a  b  c  d  e  f  g  h  i'];
      for (var r9 = 0; r9 <= 9; r9++) {
        var cells = [];
        for (var c9 = 0; c9 <= 8; c9++) {
          var piece = board[from9x10(r9, c9)];
          cells.push(piece === t.Sq.EMPTY ? ' .' : ' ' + t.PIECE_TO_FEN[piece]);
        }
        out.push(r9 + ' ' + cells.join(''));
      }
      return out.join('\n');
    }
    
    function selfTest() {
      var board = initBoard();
      var fen = serializeFEN(board, t.Color.RED);
      return fen === 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1';
    }
    
    module.exports = {
      initBoard, to9x10, from9x10,
      genMoves, getLegalMoves, hasLegalMoves,
      makeMove, applyMove, undoMove,
      findKing, forEachPiece,
      isInCheck, flyingGeneral, isCheckmate, isStalemate,
      serializeFEN, deserializeFEN, printBoard, selfTest,
    };
    
    });
    __def("history", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 行走历史条（主页面右侧，shell.overlay 第二条目）
    // 0.2.0：用户要求「行走历史迁移到主页面的右侧，上方是最新的行动」——
    // 从棋盘浮窗里拿出来，做成固定在主窗口右侧中间的窄条，最新一手在最上面（倒序）。
    // 与棋盘浮窗同生命周期：面板打开时显示，关闭时消失；数据走 core.store。
    var react = require('react');
    var core = require('core');
    
    function HistoryPanel() {
      var tickState = react.useState(0);
      var setTick = tickState[1];
    
      react.useEffect(function () {
        function onEvt() { setTick(function (x) { return x + 1; }); }
        window.addEventListener(core.PANEL_EVENT, onEvt);
        return function () { window.removeEventListener(core.PANEL_EVENT, onEvt); };
      }, []);
    
      if (!core.panelState.open) return null;
    
      var s = core.store;
      var items = [];
      if (!s.moveHistory.length) {
        items.push(react.createElement('p', { key: 'empty', style: { margin: '4px 0', fontSize: 12, color: 'var(--dsw-alias-label-tertiary, #999)' } }, '暂无记录'));
      } else {
        // 倒序：最新在上，以此类推
        for (var i = s.moveHistory.length - 1; i >= 0; i--) {
          var isRed = i % 2 === 0;
          items.push(react.createElement('div', {
            key: i,
            style: {
              display: 'flex', gap: 8, alignItems: 'baseline', padding: '4px 0',
              borderBottom: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.12))',
            },
          },
            react.createElement('span', {
              style: { minWidth: 20, fontSize: 11, color: 'var(--dsw-alias-label-tertiary, #999)', flex: 'none' },
            }, Math.floor(i / 2) + 1 + (isRed ? '红' : '黑')),
            react.createElement('span', {
              style: { fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
            }, core.formatMove(s.moveHistory[i]))));
        }
      }
    
      return react.createElement('div', {
        style: {
          position: 'fixed', right: 10, top: '50%', transform: 'translateY(-50%)',
          zIndex: 2900, width: 236, maxWidth: 'calc(100vw - 24px)',
          maxHeight: '70vh', overflowY: 'auto',
          background: 'var(--dsw-alias-bg-layer-3, #ffffff)',
          color: 'var(--dsw-alias-label-primary, inherit)',
          border: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.35))',
          borderRadius: 12, boxShadow: '0 10px 32px rgba(0,0,0,0.25)',
          fontFamily: 'system-ui, -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif',
          fontSize: 12, padding: '10px 12px', userSelect: 'none',
        },
      },
        react.createElement('div', {
          style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
        },
          react.createElement('span', { style: { fontWeight: 600, fontSize: 13 } }, '落子记录'),
          react.createElement('span', { style: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary, #999)' } },
            s.moveHistory.length ? s.moveHistory.length + ' 手' : '') ),
        items);
    }
    
    module.exports = { HistoryPanel };
    
    });
    __def("lines", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 莉娅台词池（静态数据）
    // 移植自 chess-xq（web/src/assets/lines.ts）。原 web 版定义了但从未接线，
    // 本插件把它接进对局事件（开局/将军/吃子/过河/残局/胜负/思考/悔棋……）。
    // pick()：从一组台词里随机挑一句。
    
    var LINES = {
      opening: [
        '哼，开局还想占本天使便宜？',
        '阁下可要想清楚了再走。',
        '红先黑后，输了不哭。',
        '让阁下先走，免得说本天使欺负人。',
        '这棋盘……比本天使的素描本还干净。',
        '摆好了。阁下最好别让本天使等太久。',
        '这场赢了之后，阁下请本天使吃布丁不过分吧？',
        '炮放这儿，马放那儿——阁下自己看着办。',
        '很久没有认真跟人下过棋了。阁下是认真的吧？',
        '本天使不会因为阁下走得差就放水的。先说清楚。',
        '阁下要是这局赢了，本天使可以考虑少骂你两句。',
        '星砂素描本今天空了一页——正好用来记阁下的惨状。',
        '十步之内叫阁下哭。不，五步。',
        '开始了。阁下先走——这是本天使给你最后的慈悲。',
      ],
      check: [
        '将！——别慌，本天使故意的。',
        '将军！现在求饶还来得及。',
        '呵，阁下是没看到这步棋吗？',
        '将军。阁下最好认真想想。',
        '将！建议阁下先解将再想别的。',
        '看到这步棋的时候，阁下心里是不是咯噔了一下？',
        '将。本天使就问一句：你慌不慌。',
        '将了你一军。阁下准备怎么解。',
        '不要慌。好吧，你可以慌。',
        '这步叫『阁下现在应该很后悔』。',
        '一般棋手到这一步就开始冒冷汗了。本天使在观察阁下。',
        '将杀在即，阁下有什么遗言——不对，有什么要说的吗？',
      ],
      playerCheck: [
        '哦？将军？有意思。',
        '有点意思。',
        '阁下居然也会将军。',
        '好好好，这步本天使记下了。',
        '行行行，阁下厉害。本天使这就认真起来。',
        '哼，走得还行。——还行而已，别得意。',
        '啊，这步确实没算到。阁下偶尔也能走点好棋嘛。',
        '不错。本天使承认这步有水平。',
        '将得好——但是没用。',
        '阁下这步……好吧，本天使收回之前说的一半坏话。',
      ],
      capture: [
        '吃。阁下也不心疼一下自己的子。',
        '这子归本天使了。',
        '送上门来的，不客气了。',
        '阁下是不是忘了本天使的炮能翻山。',
        '谢谢阁下的慷慨。',
        '吃掉了。阁下的表情现在一定很好看。',
        '本天使的棋子吃进去就不会吐出来。阁下最好记住。',
        '又吃一个。阁下确定还要继续吗？',
        '这子放这儿就是等着被吃的，阁下自己不注意怪谁。',
        '吃得有点不好意思了——不，完全没有。',
        '阁下有没有想过，也许不该把子送到本天使嘴边？',
        '下一个轮到谁呢……阁下猜猜看。',
      ],
      playerCapture: [
        '行，让阁下吃一个。',
        '这步不错——虽然是蒙的。',
        '吃到了，然后呢。',
        '阁下也就只能吃到这里了。',
        '好棋……本天使不喜欢说好棋，但这步确实好棋。',
        '这步走完阁下是不是觉得自己又行了？',
        '吃个棋子而已，看把你高兴的。',
        '阁下吃棋的声音比本天使想象中自信。',
        '这一个子让给阁下了。后面的可没这么容易。',
        '用了这么多步才吃到本天使一个子，效率有待提高。',
      ],
      gameOver: [
        '将杀。阁下，承让了。',
        '这局是本天使赢了。不是针对阁下，是本来就会赢。',
        '阁下还需要多练练。',
        '绝杀。还有想说的话吗？',
        '赢了也没想象中那么开心。',
        '看吧，本天使说什么来着。',
        '这局结束得太快了。阁下下次能撑久一点吗？',
        '胜败乃兵家常事——但阁下输的次数多了就不是常事了。',
        '星砂素描本记下了。这页就留着，阁下以后翻到还能回味。',
        '本天使赢了。想恭喜的话直接说，不用拐弯抹角。',
        '阁下辛苦了——虽然努力了也没什么用。',
        '好无趣的胜利……阁下能不能哪天让本天使认真一下？',
        '赢了，但没有特别开心。阁下欠本天使一场真正的对局。',
        '本天使把胜利收下了，阁下把教训收好。',
      ],
      playerWin: [
        '阁下赢了。本天使需要调整一下。',
        '行吧，这局阁下赢了。',
        '本天使承认，阁下这局走得不错。',
        '赢了就赢了，别得意。再来。',
        '这次是阁下赢了——下次就不一定了。',
        '本天使也有失手的时候。阁下别太骄傲。',
        '好吧……你赢了。本天使认。',
        '行。这局阁下走得确实好，本天使不找借口。',
        '愿赌服输。本天使不会耍赖的。',
        '阁下的成长速度比本天使预想中快。有一点……意外。',
        '本天使输了。没什么好说的。再来一局。',
        '赢了也别得意，本天使只是今天状态不好。——好吧，借口有点烂。',
        '阁下是真的赢了的。本天使没有放水。',
        '好……好！这局是本天使输了。阁下满意了吧？',
      ],
      draw: [
        '和棋。也行，本天使今天心情好。',
        '困毙。这局算阁下运气好。',
        '平局。再来一局？',
        '和棋……阁下觉得这样就完了？',
        '没赢没输，不痛快。再来。',
        '平局是本天使最不喜欢的结果——胜负就该分清楚。',
        '阁下觉得和棋就很满意了？本天使不觉得。再来。',
      ],
      thinking: [
        '让本天使想想……',
        '哼，这步不太好算……',
        '阁下稍等。',
        '别催，在想呢。',
        '这棋有点意思，让本天使算清楚。',
        '本天使正在脑内模拟后面所有可能。阁下最好坐稳。',
        '等一下，本天使在思考一条阁下绝对想不到的路。',
        '别急。好棋值得等。',
        '嗯……哼……唔……好了，本天使想好了。',
        '让本天使看看怎么折磨阁下比较好。',
        '这个局面……阁下是不是觉得自己很安全？',
        '本天使在计算一条绕过阁下所有防线的路线。快了。',
        '好难选。这步棋和那步棋都很好——全都能要阁下的命。',
        '阁下这一步留给本天使的选项太多了。选哪个好呢。',
        '稍等，本天使在欣赏阁下把自己逼入绝境的艺术。',
      ],
      firstBlood: [
        '第一条血。棋盘见红了。',
        '第一刀。后面还多的是。',
        '见血了。这局正式开始了。',
        '第一个子倒下——战场上没有无辜者。',
        '首杀到手。阁下有什么想说的？',
        '先下一城。阁下最好习惯这种感觉。',
        '棋盘上的第一声惨叫。阁下听到了吗？',
        '开局见血，这局不会太平了。',
        '第一滴血——后面还有更多。',
        '开门红。阁下看起来不太高兴。',
      ],
      playerRetreat: [
        '退回去了？阁下也有怕的时候。',
        '防守是什么战术？本天使不太了解。',
        '阁下退一步，本天使就进一步。',
        '撤子——看来阁下发现危险了。',
        '回防是明智的，但不够有意思。',
        '退了。行，本天使等你回来。',
        '这一步缩得太明显了。阁下被本天使吓到了？',
        '往后走？算阁下机灵。',
        '退守可赢不了本天使。',
        '守势也不错——至少比盲目进攻强。',
      ],
      trade: [
        '兑子。一换一，本天使不亏。',
        '换子。阁下觉得划算就行。',
        '一换一，各拿各的。',
        '等价交换——本天使不讨厌公平对决。',
        '兑掉了。剩下的子该见真章了。',
        '换了一颗子。棋盘上越来越干净了。',
        '以子换子，以命换命。阁下准备好了吗？',
        '公平交易。不过本天使从来不在交易中吃亏。',
        '兑子之后局面更清晰了——对阁下未必是好事。',
        '换得好。这局越来越有意思了。',
      ],
      pawnCross: [
        '兵过河了。是勇还是莽，本天使拭目以待。',
        '卒子过河顶个车。本天使会盯着的。',
        '过河了。小兵也有大梦想。',
        '卒子过河，不回头了。阁下最好别让它走到底线。',
        '过河兵——棋盘上最危险的弱小存在。',
        '一个兵过河了。本天使看看它能走多远。',
        '阁下很擅长用小兵制造麻烦。',
        '过河。这步走得可以——本天使勉强承认。',
        '小兵过河，后患无穷。阁下知道这句话吗？',
        '过河兵……本天使的砲不喜欢被近身。',
      ],
      endgame: [
        '子不多了。该决战了。',
        '残局。这时候一步错满盘输。阁下打起精神。',
        '棋盘上没几个子了——胜负就在这几步之间。',
        '残局了。之前的都是热身。',
        '少子残局，拼的是计算力。阁下算得过本天使吗？',
        '该结束了。本天使不喜欢拖太久。',
        '棋盘空旷了。剩下的每一步都致命。',
        '残局。这才是本天使最擅长的领域。',
        '缩小的棋盘上只有真本事才站得住。',
        '终于到残局了。本天使等这一刻很久了。',
        '棋子越少，刀刃越近。阁下感觉到了吗？',
      ],
      blunder: [
        '阁下这步……是认真的吗？',
        '这步棋走得本天使都不知道怎么夸你了。',
        '阁下是故意走这步的？本天使没看明白。',
        '这步——本天使建议阁下再想想。',
        '阁下是不是困了？这步不像阁下的水平。',
        '本天使看不懂这步的意图。阁下自己能解释吗？',
        '下到这里阁下走这个？本天使有点失望。',
        '这手棋让本天使怀疑阁下前面的运气成分。',
        '这种棋也走得出来？阁下今天状态不对吧。',
        '阁下确定？……好吧，本天使不劝了。',
        '本天使觉得阁下刚才是不是手滑了。',
        '这步走了等于没走——不，比没走还糟。',
      ],
      undo: [
        '悔棋？行，本天使就当刚才那步没发生。',
        '撤回去重走——阁下还挺会给自己找机会。',
        '本天使的落子被阁下吃回去了。记着，只有一次。',
        '悔棋说明阁下开始认真了。早该如此。',
        '行，退回去。本天使的耐心是有限的。',
      ],
      no_moves: ['本天使无棋可走了……'],
    };
    
    function pick(arr) {
      if (!arr || !arr.length) return '';
      return arr[Math.floor(Math.random() * arr.length)];
    }
    
    module.exports = { LINES, pick };
    
    });
    __def("panel", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 对局浮窗面板（shell.overlay，可拖拽）
    // 仿 dsh-puzzle panel.js：useState tick 订阅 core.rerender + PANEL_EVENT；
    // 所有状态走 core.store，操作走 core.*（改状态 → 上报 host → bump）。
    var react = require('react');
    var core = require('core');
    var boardMod = require('board');
    var t = require('types');
    
    function ChessPanel() {
      var tickState = react.useState(0);
      var setTick = tickState[1];
    
      react.useEffect(function () {
        core.rerender.fn = setTick;
        function onEvt() { setTick(function (x) { return x + 1; }); }
        window.addEventListener(core.PANEL_EVENT, onEvt);
        return function () {
          core.rerender.fn = null;
          window.removeEventListener(core.PANEL_EVENT, onEvt);
        };
      }, []);
    
      if (!core.panelState.open) return null;
    
      var s = core.store;
      var canUndo = s.moveHistory.length >= 2 && s.currentColor === t.Color.RED && s.status === 'playing';
    
      // 状态文案
      var statusText;
      if (s.status === 'red_win') statusText = '🎉 恭喜阁下获胜！';
      else if (s.status === 'black_win') statusText = '😔 阁下落败了...';
      else if (s.status === 'draw') statusText = '🤝 和棋！';
      else statusText = s.currentColor === t.Color.RED ? '阁下执红，请落子' : 'AI 执黑，思考中…';
    
      var btnStyle = {
        font: 'inherit', fontSize: 12, lineHeight: '1.4', padding: '3px 10px', borderRadius: 8,
        border: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.35))',
        background: 'var(--dsw-alias-bg-layer-1, rgba(255,255,255,0.6))',
        color: 'var(--dsw-alias-label-primary, inherit)', cursor: 'pointer',
      };
      var btnDisabled = Object.assign({}, btnStyle, { opacity: 0.45, cursor: 'not-allowed' });
    
      // 莉娅气泡：工具发来的话优先，其次对局台词
      var lastMsg = s.messages.length ? s.messages[s.messages.length - 1] : null;
      var bubbleEl = null;
      if (lastMsg) {
        bubbleEl = react.createElement('div', {
          style: {
            marginBottom: 8, fontSize: 12, lineHeight: '1.5',
            background: 'linear-gradient(90deg, rgba(255,209,220,0.92), rgba(251,194,235,0.92))',
            color: '#43223f', padding: '6px 10px', borderRadius: '10px 10px 10px 2px',
          },
        }, '莉娅：' + lastMsg.text);
      } else if (s.liyaLine) {
        bubbleEl = react.createElement('div', {
          style: {
            marginBottom: 8, fontSize: 12, lineHeight: '1.5',
            color: 'var(--dsw-alias-label-secondary, #888)',
            padding: '2px 2px', borderRadius: 8, fontStyle: 'italic',
          },
        }, '✦ ' + s.liyaLine);
      }
    
      // 存档列表
      var saveNodes = null;
      if (s.showSaves) {
        var items = [];
        if (!s.saves.length) {
          items.push(react.createElement('p', { key: 'empty', style: { margin: 0, fontSize: 12, color: 'var(--dsw-alias-label-tertiary, #999)' } }, '还没有存档'));
        } else {
          s.saves.forEach(function (sv) {
            items.push(react.createElement('div', {
              key: sv.id,
              style: {
                display: 'flex', alignItems: 'center', gap: 8, padding: '6px 8px', marginBottom: 6,
                background: 'var(--dsw-alias-bg-layer-1, rgba(255,255,255,0.5))',
                borderRadius: 8,
              },
            },
              react.createElement('div', { style: { flex: '1 1 auto', minWidth: 0 } },
                react.createElement('div', { style: { fontSize: 12, color: 'var(--dsw-alias-label-secondary, #777)' } }, sv.date),
                react.createElement('div', { style: { fontSize: 12 } }, sv.summary)),
              react.createElement('button', { type: 'button', style: btnStyle, onClick: function (id) { return function () { core.loadGame(id); }; }(sv.id) }, '加载'),
              react.createElement('button', {
                type: 'button',
                style: Object.assign({}, btnStyle, { color: 'var(--dsw-alias-state-danger-primary, #e5484d)' }),
                onClick: function (id) { return function () { core.deleteSave(id); }; }(sv.id),
              }, '删除')));
          });
        }
        saveNodes = react.createElement('div', { style: { marginTop: 6, padding: 8, borderRadius: 10, border: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.2))' } },
          react.createElement('div', { style: { marginBottom: 6, fontSize: 12, fontWeight: 600 } }, '存档列表'), items);
      }
    
      // 胜负遮罩
      var overlay = null;
      if (s.status !== 'playing') {
        var oc;
        if (s.status === 'red_win') oc = { title: '🏆 胜利！', msg: '恭喜阁下击败本天使，荣登天界棋圣！', bg: 'linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)' };
        else if (s.status === 'black_win') oc = { title: '💔 失利', msg: '阁下落败了，但胜败乃兵家常事，再接再厉！', bg: 'linear-gradient(135deg, #c62828 0%, #8e0000 100%)' };
        else oc = { title: '🤝 和棋', msg: '双方势均力敌，平局收场，乃君子之战！', bg: 'linear-gradient(135deg, #e65100 0%, #bf360c 100%)' };
        overlay = react.createElement('div', {
          style: {
            position: 'absolute', inset: 0, background: oc.bg, borderRadius: 10,
            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
            gap: 8, color: '#fff', zIndex: 5, textAlign: 'center', padding: 16,
          },
        },
          react.createElement('div', { style: { fontSize: 20, fontWeight: 700 } }, oc.title),
          react.createElement('div', { style: { fontSize: 12, lineHeight: '18px', opacity: 0.9, maxWidth: 260 } }, oc.msg),
          react.createElement('div', { style: { fontSize: 12, opacity: 0.85, fontStyle: 'italic' } }, '「' + (s.liyaLine || '…') + '」'),
          react.createElement('button', { type: 'button', onClick: core.newGame, style: Object.assign({}, btnStyle, { background: 'rgba(255,255,255,0.22)', color: '#fff', borderColor: 'rgba(255,255,255,0.4)', marginTop: 6 }) }, '再来一局'));
      }
    
      // AI 思考指示
      var thinkingEl = null;
      if (s.aiThinking && s.status === 'playing') {
        thinkingEl = react.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 8, marginTop: 8, fontSize: 12, color: 'var(--dsw-alias-label-secondary, #888)' } },
          react.createElement('span', { style: {
            width: 12, height: 12, borderRadius: '50%', flex: 'none',
            border: '2px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.3))',
            borderTopColor: 'var(--dsw-alias-label-primary, #444)',
            animation: 'dsh-chess-spin 0.8s linear infinite',
          } }),
          '本天使思考中…');
      }
    
      // 面板定位：记忆上次位置（0.2.0 修「界面不固定」），没有则默认右上角；
      // 行走历史已迁到主页面右侧（history.js），本面板只留棋盘+控制
      if (!core.panelState.pos) {
        core.panelState.pos = core.loadPos() || {
          x: Math.max(8, (window.innerWidth || 1200) - 560),
          y: Math.max(8, 70),
        };
      }
      var pos = core.panelState.pos;
    
      function onHeaderDown(ev) {
        if (ev.button !== 0) return;
        ev.preventDefault();
        var sx = ev.clientX, sy = ev.clientY;
        var bx = pos.x, by = pos.y;
        function onMove(mv) {
          core.panelState.pos = { x: bx + (mv.clientX - sx), y: by + (mv.clientY - sy) };
          core.bump();
        }
        function onUp() {
          window.removeEventListener('mousemove', onMove);
          window.removeEventListener('mouseup', onUp);
          core.savePos(); // 拖完落盘，下次打开还在老位置
        }
        window.addEventListener('mousemove', onMove);
        window.addEventListener('mouseup', onUp);
      }
    
      var controls = react.createElement('div', { style: { display: 'flex', gap: 6, flexWrap: 'wrap', margin: '8px 0' } },
        react.createElement('button', { type: 'button', style: btnStyle, onClick: core.newGame }, '重新开始'),
        react.createElement('button', {
          type: 'button',
          style: canUndo ? btnStyle : btnDisabled,
          disabled: !canUndo,
          onClick: core.undo,
        }, '悔棋'),
        react.createElement('button', { type: 'button', style: btnStyle, onClick: core.saveGame }, '保存'),
        react.createElement('button', {
          type: 'button',
          style: btnStyle,
          onClick: function () { s.showSaves = !s.showSaves; core.bump(); },
        }, s.showSaves ? '收起存档' : '存档'));
    
      return react.createElement('div', {
        style: {
          position: 'fixed', left: pos.x, top: pos.y, zIndex: 3000,
          width: 540, maxWidth: 'calc(100vw - 16px)',
          maxHeight: 'calc(100vh - 24px)', overflowY: 'auto',
          background: 'var(--dsw-alias-bg-layer-3, #ffffff)',
          color: 'var(--dsw-alias-label-primary, inherit)',
          border: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.35))',
          borderRadius: 14, boxShadow: '0 12px 40px rgba(0,0,0,0.3)',
          fontFamily: 'system-ui, -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif',
          fontSize: 13, userSelect: 'none',
        },
      },
        react.createElement('div', {
          onMouseDown: onHeaderDown,
          style: {
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '10px 14px', cursor: 'move',
            borderBottom: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.2))',
            background: 'linear-gradient(90deg, rgba(255,209,220,0.35), rgba(251,194,235,0.35))',
            borderRadius: '14px 14px 0 0',
          },
          title: '按住标题可拖动',
        },
          react.createElement('span', { style: { fontWeight: 600, fontSize: 14 } }, '♟ 天界象棋'),
          react.createElement('button', {
            type: 'button',
            onClick: function () { core.setPanelOpen(false); },
            style: {
              border: 0, background: 'transparent', cursor: 'pointer',
              color: 'var(--dsw-alias-label-tertiary, #999)', fontSize: 15, padding: '2px 6px',
            },
          }, '✕')),
        react.createElement('div', { style: { padding: '6px 14px 14px' } },
          bubbleEl,
          react.createElement('div', { style: { fontSize: 14, fontWeight: 600 } }, statusText),
          react.createElement('div', { style: { position: 'relative', width: 'max-content', maxWidth: '100%', margin: '6px auto 0' } },
            react.createElement(boardMod.Board, {
              board: s.board,
              onCellClick: core.handleCell,
              selectedSquare: s.selected,
              legalMoves: s.legalMoves,
              lastMove: s.lastMove,
            }),
            overlay),
          controls,
          saveNodes,
          thinkingEl));
    }
    
    module.exports = { ChessPanel };
    
    });
    __def("types", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 中国象棋常量与基础函数
    // 移植自 chess-xq（web/src/game/types.ts）：
    // 棋盘用 17×14 哨兵数组，有效区 9×10（row/col 偏移 3）；棋子编码：bit3 = 颜色，低 3 位 = 兵种。
    // 红方在下（row 9 是红底线），黑方在上（row 0 是黑底线）。
    var ROWS = 17;
    var COLS = 14;
    var BOARD_SIZE = ROWS * COLS;
    
    var Sq = { SENTINEL: -1, EMPTY: 0 };
    
    var ROW_OFFSET = 3;
    var COL_OFFSET = 3;
    
    var RED_PALACE = { rowMin: 7, rowMax: 9, colMin: 3, colMax: 5 };
    var BLK_PALACE = { rowMin: 0, rowMax: 2, colMin: 3, colMax: 5 };
    
    var Color = { RED: 0, BLACK: 1 };
    var OPPOSITE = { 0: 1, 1: 0 };
    
    var PieceType = { KING: 1, ADVISOR: 2, BISHOP: 3, KNIGHT: 4, ROOK: 5, CANNON: 6, PAWN: 7 };
    
    var Piece = {
      K_RED: 1, A_RED: 2, B_RED: 3, N_RED: 4, R_RED: 5, C_RED: 6, P_RED: 7,
      K_BLK: 9, A_BLK: 10, B_BLK: 11, N_BLK: 12, R_BLK: 13, C_BLK: 14, P_BLK: 15,
    };
    
    function colorOf(piece) { return (piece >> 3) & 1; }
    function typeOf(piece) { return piece & 7; }
    function oppositeColor(c) { return c === Color.RED ? Color.BLACK : Color.RED; }
    
    // 9×10 坐标 <-> 17×14 哨兵数组下标
    function sqIdx(row9x10, col9x10) { return (row9x10 + ROW_OFFSET) * COLS + (col9x10 + COL_OFFSET); }
    function sqToRC(sq) { return [Math.floor(sq / COLS) - ROW_OFFSET, (sq % COLS) - COL_OFFSET]; }
    function inBoard(r, c) { return r >= 0 && r <= 9 && c >= 0 && c <= 8; }
    
    var KNIGHT_MOVES = [
      [-2, -1, -1, 0], [-2, 1, -1, 0],
      [-1, -2, 0, -1], [-1, 2, 0, 1],
      [1, -2, 0, -1], [1, 2, 0, 1],
      [2, -1, 1, 0], [2, 1, 1, 0],
    ];
    
    var ADVISOR_DELTAS = [[-1, -1], [-1, 1], [1, -1], [1, 1]];
    
    var BISHOP_MOVES = [
      [-2, -2, -1, -1], [-2, 2, -1, 1],
      [2, -2, 1, -1], [2, 2, 1, 1],
    ];
    
    var LINE_DIRS = [[-1, 0], [1, 0], [0, -1], [0, 1]];
    var KING_DIRS = [[-1, 0], [1, 0], [0, -1], [0, 1]];
    
    var PIECE_TO_FEN = {
      1: 'K', 2: 'A', 3: 'B', 4: 'N', 5: 'R', 6: 'C', 7: 'P',
      9: 'k', 10: 'a', 11: 'b', 12: 'n', 13: 'r', 14: 'c', 15: 'p',
    };
    
    var FEN_TO_PIECE = {
      'K': 1, 'A': 2, 'B': 3, 'N': 4, 'R': 5, 'C': 6, 'P': 7,
      'k': 9, 'a': 10, 'b': 11, 'n': 12, 'r': 13, 'c': 14, 'p': 15,
    };
    
    var PIECE_CN = {
      1: '帅', 2: '仕', 3: '相', 4: '马', 5: '车', 6: '炮', 7: '兵',
      9: '将', 10: '士', 11: '象', 12: '马', 13: '车', 14: '砲', 15: '卒',
    };
    
    module.exports = {
      ROWS, COLS, BOARD_SIZE, Sq, ROW_OFFSET, COL_OFFSET,
      RED_PALACE, BLK_PALACE, Color, OPPOSITE, PieceType, Piece,
      colorOf, typeOf, oppositeColor, sqIdx, sqToRC, inBoard,
      KNIGHT_MOVES, ADVISOR_DELTAS, BISHOP_MOVES, LINE_DIRS, KING_DIRS,
      PIECE_TO_FEN, FEN_TO_PIECE, PIECE_CN,
    };
    
    });
    __def("ui", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 小 UI 组件（输入框开关 + 设置页）
    // InputToggle：conversation.input.left 常驻开关（仿 dsh-puzzle，入口只留一个）。
    // ChessSettings：settings.section —— AI 难度设置 + 当前局摘要（数据 fetch + 本地 useState）。
    var react = require('react');
    var core = require('core');
    
    function InputToggle() {
      var tickState = react.useState(0);
      var setTick = tickState[1];
      react.useEffect(function () {
        function onEvt() { setTick(function (x) { return x + 1; }); }
        window.addEventListener(core.PANEL_EVENT, onEvt);
        return function () { window.removeEventListener(core.PANEL_EVENT, onEvt); };
      }, []);
      return react.createElement('button', {
        type: 'button',
        title: '天界象棋',
        'aria-label': '天界象棋',
        'aria-expanded': core.panelState.open,
        onClick: core.togglePanel,
        style: {
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          width: 26, height: 26, borderRadius: 7, cursor: 'pointer', padding: 0,
          border: '1px solid var(--dsw-alias-border-l2, rgba(128,128,128,0.3))',
          background: core.panelState.open ? 'var(--dsw-alias-interactive-bg-hover, rgba(128,128,128,0.15))' : 'transparent',
          color: 'var(--dsw-alias-label-primary, inherit)',
          fontSize: 14, lineHeight: 1, flex: 'none',
        },
      }, '♟');
    }
    
    var DIFF_LABELS = { 1: '萌新（1 层）', 2: '入门（2 层）', 3: '认真（3 层）', 4: '全力（4 层）' };
    
    function ChessSettings() {
      var cfgState = react.useState({ aiDepth: 3 });
      var cfg = cfgState[0];
      var setCfg = cfgState[1];
      var repState = react.useState(null);
      var rep = repState[0];
      var setRep = repState[1];
      var errState = react.useState('');
      var error = errState[0];
      var setError = errState[1];
    
      function loadAll() {
        fetch('/dsh-chess/state', { cache: 'no-store' })
          .then(function (r) { return r.ok ? r.json() : null; })
          .then(function (d) {
            if (!d) return;
            if (d.config && typeof d.config === 'object') setCfg(d.config);
            if (d.report && typeof d.report === 'object') setRep(d.report);
          })
          .catch(function () {});
      }
    
      react.useEffect(function () {
        loadAll();
        var id = setInterval(loadAll, 2000);
        return function () { clearInterval(id); };
      }, []);
    
      function setDepth(n) {
        setError('');
        fetch('/dsh-chess/config', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ aiDepth: n }),
        })
          .then(function (r) { return r.json(); })
          .then(function (d) { if (d && d.config) setCfg(d.config); })
          .catch(function () { setError('保存失败（Host 路由不可达）'); });
      }
    
      function newGame() {
        setError('');
        fetch('/dsh-chess/cmd', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ cmd: 'new_game' }),
        }).catch(function () { setError('发起失败（Host 路由不可达）'); });
      }
    
      var btnStyle = {
        cursor: 'pointer', font: 'inherit', fontSize: 13,
        color: 'var(--dsw-alias-label-primary)', background: 'var(--dsw-alias-bg-layer-3)',
        border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 8, padding: '5px 12px',
      };
    
      var depthOpts = [1, 2, 3, 4].map(function (n) {
        return react.createElement('option', { key: n, value: String(n) }, DIFF_LABELS[n]);
      });
    
      var nodes = [
        react.createElement('h2', { key: 'head', style: { margin: '0 0 8px', fontSize: 16, fontWeight: 600 } }, '天界象棋'),
        react.createElement('p', { key: 'tip', style: { margin: '0 0 10px', fontSize: 14, lineHeight: '22px', color: 'var(--dsw-alias-label-secondary)' } },
          '中国象棋人机对战：阁下执红先手，本天使执黑。点输入框左侧「♟」打开对局面板，可悔棋、存档、调 AI 难度。'),
      ];
    
      if (rep) {
        var turnText = rep.turn === 0 ? '红方走（阁下）' : '黑方走（本天使）';
        var statusText = rep.status === 'playing' ? ('进行中 · ' + turnText)
          : rep.status === 'red_win' ? '红方胜'
          : rep.status === 'black_win' ? '黑方胜'
          : '和棋';
        nodes.push(react.createElement('div', { key: 'now', style: { marginBottom: 12, padding: '10px 14px', borderRadius: 12, border: '1px solid var(--dsw-alias-border-l2)', background: 'var(--dsw-alias-bg-layer-1)' } },
          react.createElement('div', { style: { fontSize: 13, color: 'var(--dsw-alias-label-secondary)' } }, '当前局'),
          react.createElement('div', { style: { fontSize: 15, fontWeight: 600, marginTop: 2 } }, statusText),
          react.createElement('div', { style: { marginTop: 4, fontSize: 13, color: 'var(--dsw-alias-label-tertiary)' } },
            '已走 ' + rep.moves + ' 步' + (rep.aiThinking ? ' · 本天使思考中' : ''))));
      }
    
      nodes.push(react.createElement('div', { key: 'depth', style: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 } },
        react.createElement('span', { style: { fontSize: 13 } }, 'AI 难度'),
        react.createElement('select', {
          value: String(cfg.aiDepth || 3),
          onChange: function (ev) { setDepth(Number(ev.target.value)); },
          style: Object.assign({}, btnStyle, { cursor: 'pointer' }),
        }, depthOpts),
        react.createElement('button', { type: 'button', onClick: newGame, style: btnStyle }, '♟ 新开一局')));
    
      if (error) {
        nodes.push(react.createElement('div', { key: 'err', style: { marginBottom: 10, padding: '8px 12px', borderRadius: 10, fontSize: 13, color: 'var(--dsw-alias-state-danger-primary, #e5484d)', border: '1px solid var(--dsw-alias-state-danger-primary, #e5484d)', background: 'var(--dsw-alias-bg-layer-1)' } }, error));
      }
    
      nodes.push(react.createElement('p', { key: 'hint', style: { margin: '10px 0 0', fontSize: 12, lineHeight: '18px', color: 'var(--dsw-alias-label-tertiary)' } },
        '本天使可以发话到棋盘（chess_talk）、查看对局进展（chess_state）、直接开新局（chess_new_game）。存档存在浏览器本地（localStorage）。'));
    
      return react.createElement('div', { key: 'dsh-chess-xq', style: { padding: '4px 0', color: 'var(--dsw-alias-label-primary)' } }, nodes);
    }
    
    module.exports = { InputToggle, ChessSettings };
    
    });
    __def("entry", function (module, exports, require) {
    // dsh-chess-xq —— client 半 · 插件入口（bundle 导出：inject / apply）
    // 职责：apply 期建 1s 轮询（跨组件重挂载存活）+ 开局/首拉 + 四个槽位注册：
    //   conversation.input.left（♟ 小开关）/ shell.overlay（对局浮窗）/ shell.overlay（右侧行走历史）/
    //   settings.section（难度设置）。
    // 纯编排：逻辑全在 core.js，组件全在 panel.js / history.js / ui.js。
    var react = require('react');
    var core = require('core');
    var Panel = require('panel');
    var History = require('history');
    var UI = require('ui');
    
    exports.inject = ['slots'];
    exports.apply = function (ctx) {
      // 轮询一次建好（跨面板/设置页重挂载存活）；ctx.effect 卸载自动清理
      ctx.effect(function () {
        var id = setInterval(core.pollTick, core.POLL_MS);
        return function () { clearInterval(id); };
      }, 'dsh-chess-xq: poll');
    
      // 初始局 + 首拉（拉回配置的 AI 深度/消息）
      core.boot();
    
      // 注入对局浮窗用到的极简 CSS（思考转圈动画），卸载时移除
      ctx.effect(function () {
        var style = document.createElement('style');
        style.id = 'dsh-chess-xq-style';
        style.textContent = '@keyframes dsh-chess-spin { to { transform: rotate(360deg); } }';
        document.head.appendChild(style);
        return function () {
          if (style.parentNode) style.parentNode.removeChild(style);
        };
      }, 'dsh-chess-xq: style');
    
      var slots = ctx.get('slots');
      if (slots === undefined) return;
      // 入口只留一个：输入框工具行左端的小开关（发送框内、附件/计划旁边）
      slots.inject('conversation.input.left', function () {
        return slots.register(
          {
            name: 'conversation.input.left',
            id: 'dsh-chess-xq-toggle',
            order: 95,
            label: function () { return '天界象棋'; },
          },
          UI.InputToggle
        );
      });
      slots.inject('shell.overlay', function () {
        return slots.register(
          {
            name: 'shell.overlay',
            id: 'dsh-chess-xq-panel',
            order: 35,
            label: function () { return '天界象棋'; },
          },
          Panel.ChessPanel
        );
      });
      // 行走历史：主页面右侧固定竖条（最新在上），与棋盘浮窗同开关
      slots.inject('shell.overlay', function () {
        return slots.register(
          {
            name: 'shell.overlay',
            id: 'dsh-chess-xq-history',
            order: 36,
            label: function () { return '天界象棋·落子'; },
          },
          History.HistoryPanel
        );
      });
      slots.inject('settings.section', function () {
        return slots.register(
          {
            name: 'settings.section',
            id: 'dsh-chess-xq',
            order: 140,
            label: function () { return '天界象棋'; },
          },
          function (props) { return react.createElement(UI.ChessSettings, { ctx: ctx }); }
        );
      });
    
      console.log('[dsh-chess-xq-plugin] client loaded');
    };
    
    });
    return __req('entry');
  },
});
